# Form implementation generated from reading ui file 'resources\design.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from settings import path

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 740)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setStyleSheet("QWidget {background: rgb(1, 42, 74)}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 6px;\n"
"    background-color: rgb(42, 111, 151);\n"
"    height: 30px;\n"
"    color: white;\n"
"    font: 75 16pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton::enabled::hover {\n"
"    background-color: rgb(70, 143, 175);\n"
"}\n"
"\n"
"QPushButton::enabled:pressed {\n"
"    background-color: rgb(97, 165, 194);\n"
"}\n"
"\n"
"QPushButton::disabled {\n"
"    background: rgb(1, 58, 99);\n"
"}\n"
"\n"
"QCheckBox {\n"
"    spacing: 10px;\n"
"    color: white;\n"
"    font: 18pt \"Verdana\";\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background: rgb(1, 79, 134);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"     background: rgb(70, 143, 175);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"     background: rgb(70, 143, 175);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background: rgb(42, 111, 151);\n"
"    image: url(resources/check_mark.png);\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 6px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: white;\n"
"    height: 30;\n"
"    font: 16pt \"Verdana\";\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(42, 111, 151);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: rgb(42, 111, 151);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    background-color: rgb(42, 111, 151);\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(1, 58, 99);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 6px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 6px;\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: rgb(70, 143, 175)\n"
"}\n"
"\n"
"QComboBox::drow-down:pressed {\n"
"    background: rgb(97, 165, 194);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
f"    image: url(resources\\arrow.png);\n"
"    width: 8;\n"
"    height: 8;\n"
"}\n"
"\n"
"QComboBox::disabled {\n"
"    background: rgb(1, 58, 99);\n"
"}\n"
"\n"
"QComboBox::drop-down:disabled {\n"
"    background: rgb(1, 58, 99);\n"
"    border-left-color: rgb(1, 42, 74);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 5px solid rgb(1, 58, 99);\n"
"    border-radius: 6px;\n"
"    background: rgb(42, 111, 151);\n"
"    color: white\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: rgb(42, 111, 151);\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgb(42, 111, 151);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background-color: rgb(1, 79, 134);\n"
"}\n"
"\n"
"QTabBar::tab:!selected:pressed {\n"
"    background:  rgb(70, 143, 175);\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}\n"
"\n"
"QListView {\n"
"    border: 5px solid rgb(1, 58, 99);\n"
"    border-radius: 6px;\n"
"    background: rgb(1, 42, 74);\n"
"    color: white;\n"
"    font: 14pt \"Verdana\";\n"
"}\n"
"\n"
"QListView:item {\n"
"    color: white;\n"
"    selection-background-color: rgb(1, 73, 124);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"     width: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(42, 111, 151);\n"
"    border-radius: 2px\n"
"}\n"
"\n"
"QScrollBar:handle:vertical:pressed {\n"
"    background: rgb(70, 143, 175);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     height: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(42, 111, 151);\n"
"    border-radius: 2px\n"
"}\n"
"\n"
"QScrollBar:handle:horizontal:pressed {\n"
"    background: rgb(70, 143, 175);\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    border: none;\n"
"    width: 5px;\n"
"    height: 5px;\n"
"    background: rgb(1, 42, 74);\n"
"}\n"
"\n"
"QScrollBar::down-arrow:vertical, QScrollBar::up-arrow:vertical {\n"
"    border: none;\n"
"    width: 5px;\n"
"    height: 5px;\n"
"    background: rgb(1, 42, 74);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 5px solid rgb(1, 58, 99);\n"
"    height: 20px;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font: 12pt \"Verdana\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 7px solid rgb(1, 73, 124);\n"
"    border-radius: 8px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.sideMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.sideMenu.setGeometry(QtCore.QRect(-10, -20, 201, 781))
        self.sideMenu.setStyleSheet("QWidget {\n"
"    background-color: rgb(1, 58, 99);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 6px;\n"
"    background-color: rgb(1, 79, 134);\n"
"    height: 30px;\n"
"    color: white;\n"
"    font: 75 16pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton:unchecked {\n"
"   background-color: rgb(1, 79, 134);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"   background: rgb(42, 111, 151);\n"
"}\n"
"\n"
"")
        self.sideMenu.setObjectName("sideMenu")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.sideMenu)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 171, 721))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appLogo = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.appLogo.setText("")
        self.appLogo.setPixmap(QtGui.QPixmap(path + "resources\\treble_clef.png"))
        self.appLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appLogo.setObjectName("appLogo")
        self.verticalLayout_2.addWidget(self.appLogo)
        self.appName = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.appName.setFont(font)
        self.appName.setStyleSheet("")
        self.appName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appName.setObjectName("appName")
        self.verticalLayout_2.addWidget(self.appName)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buildMenuButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.buildMenuButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(path + "resources\\note.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buildMenuButton.setIcon(icon)
        self.buildMenuButton.setIconSize(QtCore.QSize(16, 16))
        self.buildMenuButton.setCheckable(True)
        self.buildMenuButton.setChecked(True)
        self.buildMenuButton.setObjectName("buildMenuButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.buildMenuButton)
        self.verticalLayout.addWidget(self.buildMenuButton)
        self.exerciseMenuButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(path + "resources\\brain.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exerciseMenuButton.setIcon(icon1)
        self.exerciseMenuButton.setCheckable(True)
        self.exerciseMenuButton.setChecked(False)
        self.exerciseMenuButton.setObjectName("exerciseMenuButton")
        self.buttonGroup.addButton(self.exerciseMenuButton)
        self.verticalLayout.addWidget(self.exerciseMenuButton)
        self.settingsMenuButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(path + "resources\\gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settingsMenuButton.setIcon(icon2)
        self.settingsMenuButton.setCheckable(True)
        self.settingsMenuButton.setChecked(False)
        self.settingsMenuButton.setObjectName("settingsMenuButton")
        self.buttonGroup.addButton(self.settingsMenuButton)
        self.verticalLayout.addWidget(self.settingsMenuButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.appVersion = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(False)
        font.setWeight(50)
        self.appVersion.setFont(font)
        self.appVersion.setStyleSheet("QLabel {\n"
"    color: white\n"
"}")
        self.appVersion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appVersion.setObjectName("appVersion")
        self.verticalLayout_2.addWidget(self.appVersion)
        self.buildMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.buildMenu.setGeometry(QtCore.QRect(190, 0, 821, 731))
        self.buildMenu.setObjectName("buildMenu")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(parent=self.buildMenu)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 812, 721))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.buildTabWidget = QtWidgets.QTabWidget(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buildTabWidget.setFont(font)
        self.buildTabWidget.setAutoFillBackground(False)
        self.buildTabWidget.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 20pt \"Verdana\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(1, 58, 99);\n"
"    selection-background-color: rgb(1, 42, 74);\n"
"}")
        self.buildTabWidget.setObjectName("buildTabWidget")
        self.scaleTab = QtWidgets.QWidget()
        self.scaleTab.setObjectName("scaleTab")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.scaleTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.sKeyCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.sKeyCB.setObjectName("sKeyCB")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.sKeyCB.addItem("")
        self.horizontalLayout_13.addWidget(self.sKeyCB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.sScaleCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.sScaleCB.setObjectName("sScaleCB")
        self.sScaleCB.addItem("")
        self.sScaleCB.addItem("")
        self.sScaleCB.addItem("")
        self.sScaleCB.addItem("")
        self.sScaleCB.addItem("")
        self.sScaleCB.addItem("")
        self.horizontalLayout_14.addWidget(self.sScaleCB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.buildTabWidget.addTab(self.scaleTab, "")
        self.chordTab = QtWidgets.QWidget()
        self.chordTab.setObjectName("chordTab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.chordTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 371, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.cKeyCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_3)
        self.cKeyCB.setObjectName("cKeyCB")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.cKeyCB.addItem("")
        self.horizontalLayout_7.addWidget(self.cKeyCB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.cChordCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_3)
        self.cChordCB.setObjectName("cChordCB")
        self.cChordCB.addItem("")
        self.cChordCB.addItem("")
        self.cChordCB.addItem("")
        self.cChordCB.addItem("")
        self.horizontalLayout_8.addWidget(self.cChordCB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.cAddLayout = QtWidgets.QHBoxLayout()
        self.cAddLayout.setObjectName("cAddLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.cAddLayout.addWidget(self.label_5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.cAddLayout.addItem(spacerItem6)
        self.cAddCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_3)
        self.cAddCB.setObjectName("cAddCB")
        self.cAddCB.addItem("")
        self.cAddCB.addItem("")
        self.cAddCB.addItem("")
        self.cAddCB.addItem("")
        self.cAddCB.addItem("")
        self.cAddLayout.addWidget(self.cAddCB)
        self.verticalLayout_4.addLayout(self.cAddLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.buildTabWidget.addTab(self.chordTab, "")
        self.intervalTab = QtWidgets.QWidget()
        self.intervalTab.setObjectName("intervalTab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.intervalTab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 371, 391))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.iKeyCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_4)
        self.iKeyCB.setObjectName("iKeyCB")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.iKeyCB.addItem("")
        self.horizontalLayout_10.addWidget(self.iKeyCB)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.iIntervalCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_4)
        self.iIntervalCB.setObjectName("iIntervalCB")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.iIntervalCB.addItem("")
        self.horizontalLayout_11.addWidget(self.iIntervalCB)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.buildTabWidget.addTab(self.intervalTab, "")
        self.verticalLayout_8.addWidget(self.buildTabWidget)
        self.notesLW = QtWidgets.QListWidget(parent=self.verticalLayoutWidget_5)
        self.notesLW.setObjectName("notesLW")
        self.verticalLayout_8.addWidget(self.notesLW)
        self.buildButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        self.buildButton.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(path + "resources\\check_mark.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buildButton.setIcon(icon3)
        self.buildButton.setIconSize(QtCore.QSize(14, 14))
        self.buildButton.setObjectName("buildButton")
        self.verticalLayout_8.addWidget(self.buildButton)
        self.listenButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        self.listenButton.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(path + "resources\\headphones.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.listenButton.setIcon(icon4)
        self.listenButton.setIconSize(QtCore.QSize(14, 14))
        self.listenButton.setObjectName("listenButton")
        self.verticalLayout_8.addWidget(self.listenButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.songSearchLE = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_5)
        self.songSearchLE.setStyleSheet("")
        self.songSearchLE.setObjectName("songSearchLE")
        self.verticalLayout_5.addWidget(self.songSearchLE)
        self.searchButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        self.searchButton.setEnabled(True)
        self.searchButton.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(path + "resources\\search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchButton.setIcon(icon5)
        self.searchButton.setIconSize(QtCore.QSize(14, 14))
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout_5.addWidget(self.searchButton)
        self.songsLW = QtWidgets.QListWidget(parent=self.verticalLayoutWidget_5)
        self.songsLW.setObjectName("songsLW")
        self.verticalLayout_5.addWidget(self.songsLW)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.imageView = QtWidgets.QLabel(parent=self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageView.sizePolicy().hasHeightForWidth())
        self.imageView.setSizePolicy(sizePolicy)
        self.imageView.setMinimumSize(QtCore.QSize(810, 210))
        self.imageView.setMaximumSize(QtCore.QSize(810, 210))
        self.imageView.setStyleSheet("QLabel {\n"
"    border: 5px solid rgb(1, 58, 99);\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.imageView.setText("")
        self.imageView.setObjectName("imageView")
        self.verticalLayout_6.addWidget(self.imageView)
        self.settingsMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.settingsMenu.setEnabled(True)
        self.settingsMenu.setGeometry(QtCore.QRect(200, 10, 811, 721))
        self.settingsMenu.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 20pt \"Verdana\";\n"
"}")
        self.settingsMenu.setObjectName("settingsMenu")
        self.widget = QtWidgets.QWidget(parent=self.settingsMenu)
        self.widget.setGeometry(QtCore.QRect(0, 0, 811, 681))
        self.widget.setStyleSheet("QWidget {\n"
"    border: 5px solid rgb(1, 58, 99);\n"
"    border-radius: 6px;\n"
"}")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 791, 611))
        self.widget_2.setStyleSheet("QWidget {border: none}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(parent=self.widget_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 791, 611))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.sLanguageCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_6)
        self.sLanguageCB.setObjectName("sLanguageCB")
        self.sLanguageCB.addItem("")
        self.sLanguageCB.addItem("")
        self.horizontalLayout.addWidget(self.sLanguageCB)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.sInstrumentCB = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_6)
        self.sInstrumentCB.setObjectName("sInstrumentCB")
        self.sInstrumentCB.addItem("")
        self.sInstrumentCB.addItem("")
        self.horizontalLayout_2.addWidget(self.sInstrumentCB)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.settingsMenu)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 690, 811, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sLHint = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.sLHint.setObjectName("sLHint")
        self.horizontalLayout_3.addWidget(self.sLHint)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.sResetButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sResetButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sResetButton.sizePolicy().hasHeightForWidth())
        self.sResetButton.setSizePolicy(sizePolicy)
        self.sResetButton.setMinimumSize(QtCore.QSize(120, 0))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(path + "resources\\reset.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sResetButton.setIcon(icon6)
        self.sResetButton.setObjectName("sResetButton")
        self.horizontalLayout_3.addWidget(self.sResetButton)
        self.sApplyButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sApplyButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sApplyButton.sizePolicy().hasHeightForWidth())
        self.sApplyButton.setSizePolicy(sizePolicy)
        self.sApplyButton.setMinimumSize(QtCore.QSize(120, 0))
        self.sApplyButton.setIcon(icon3)
        self.sApplyButton.setObjectName("sApplyButton")
        self.horizontalLayout_3.addWidget(self.sApplyButton)
        self.exerciseMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.exerciseMenu.setEnabled(True)
        self.exerciseMenu.setGeometry(QtCore.QRect(200, 10, 811, 721))
        self.exerciseMenu.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 20pt \"Verdana\";\n"
"}")
        self.exerciseMenu.setObjectName("exerciseMenu")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(parent=self.exerciseMenu)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 690, 811, 32))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.eAvResult = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_7)
        self.eAvResult.setObjectName("eAvResult")
        self.horizontalLayout_23.addWidget(self.eAvResult)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem15)
        self.eStartButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.eStartButton.setMinimumSize(QtCore.QSize(150, 0))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources\\resources/flag.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.eStartButton.setIcon(icon7)
        self.eStartButton.setObjectName("eStartButton")
        self.horizontalLayout_23.addWidget(self.eStartButton)
        self.eTabWidget = QtWidgets.QTabWidget(parent=self.exerciseMenu)
        self.eTabWidget.setEnabled(False)
        self.eTabWidget.setGeometry(QtCore.QRect(0, 0, 811, 681))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.eTabWidget.setFont(font)
        self.eTabWidget.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font: 20pt \"Verdana\";\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(1, 58, 99);\n"
"    selection-background-color: rgb(1, 42, 74);\n"
"}")
        self.eTabWidget.setObjectName("eTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(parent=self.tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 781, 80))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.eNListenButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_7)
        self.eNListenButton.setMinimumSize(QtCore.QSize(200, 0))
        self.eNListenButton.setIcon(icon4)
        self.eNListenButton.setObjectName("eNListenButton")
        self.horizontalLayout_4.addWidget(self.eNListenButton)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.eNComboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_7)
        self.eNComboBox.setObjectName("eNComboBox")
        self.horizontalLayout_4.addWidget(self.eNComboBox)
        self.eNSubmitButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_7)
        self.eNSubmitButton.setMinimumSize(QtCore.QSize(100, 0))
        self.eNSubmitButton.setIcon(icon3)
        self.eNSubmitButton.setObjectName("eNSubmitButton")
        self.horizontalLayout_4.addWidget(self.eNSubmitButton)
        self.eNNextButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_7)
        self.eNNextButton.setMinimumSize(QtCore.QSize(100, 0))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(path + "resources\\next.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.eNNextButton.setIcon(icon8)
        self.eNNextButton.setObjectName("eNNextButton")
        self.horizontalLayout_4.addWidget(self.eNNextButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.eNAnswer = QtWidgets.QLabel(parent=self.verticalLayoutWidget_7)
        self.eNAnswer.setObjectName("eNAnswer")
        self.verticalLayout_10.addWidget(self.eNAnswer)
        self.eTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(parent=self.tab_2)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 781, 80))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.eIListenButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_8)
        self.eIListenButton.setMinimumSize(QtCore.QSize(200, 0))
        self.eIListenButton.setIcon(icon4)
        self.eIListenButton.setObjectName("eIListenButton")
        self.horizontalLayout_6.addWidget(self.eIListenButton)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.eIComboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_8)
        self.eIComboBox.setObjectName("eIComboBox")
        self.horizontalLayout_6.addWidget(self.eIComboBox)
        self.eISubmitButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_8)
        self.eISubmitButton.setMinimumSize(QtCore.QSize(100, 0))
        self.eISubmitButton.setIcon(icon3)
        self.eISubmitButton.setObjectName("eISubmitButton")
        self.horizontalLayout_6.addWidget(self.eISubmitButton)
        self.eINextButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_8)
        self.eINextButton.setMinimumSize(QtCore.QSize(100, 0))
        self.eINextButton.setIcon(icon8)
        self.eINextButton.setObjectName("eINextButton")
        self.horizontalLayout_6.addWidget(self.eINextButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.eIAnswer = QtWidgets.QLabel(parent=self.verticalLayoutWidget_8)
        self.eIAnswer.setObjectName("eIAnswer")
        self.verticalLayout_11.addWidget(self.eIAnswer)
        self.eTabWidget.addTab(self.tab_2, "")
        self.sideMenu.raise_()
        self.buildMenu.raise_()
        self.exerciseMenu.raise_()
        self.settingsMenu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.buildTabWidget.setCurrentIndex(0)
        self.eTabWidget.setCurrentIndex(0)
        self.buildMenuButton.toggled['bool'].connect(self.buildMenu.setVisible) # type: ignore
        self.settingsMenuButton.toggled['bool'].connect(self.buildMenu.setHidden) # type: ignore
        self.exerciseMenuButton.toggled['bool'].connect(self.buildMenu.setHidden) # type: ignore
        self.settingsMenuButton.toggled['bool'].connect(self.settingsMenu.setVisible) # type: ignore
        self.buildMenuButton.toggled['bool'].connect(self.settingsMenu.setHidden) # type: ignore
        self.exerciseMenuButton.toggled['bool'].connect(self.settingsMenu.setHidden) # type: ignore
        self.buildMenuButton.toggled['bool'].connect(self.exerciseMenu.setHidden) # type: ignore
        self.exerciseMenuButton.toggled['bool'].connect(self.exerciseMenu.setVisible) # type: ignore
        self.settingsMenuButton.toggled['bool'].connect(self.exerciseMenu.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MusicTheoryAssistant"))
        self.appName.setText(_translate("MainWindow", "Music Theory Assistant"))
        self.buildMenuButton.setText(_translate("MainWindow", "Build"))
        self.exerciseMenuButton.setText(_translate("MainWindow", "Exercise"))
        self.settingsMenuButton.setText(_translate("MainWindow", "Settings"))
        self.appVersion.setText(_translate("MainWindow", "v.0.0.1"))
        self.label_9.setText(_translate("MainWindow", "Key"))
        self.sKeyCB.setItemText(0, _translate("MainWindow", "C"))
        self.sKeyCB.setItemText(1, _translate("MainWindow", "C#\\Db"))
        self.sKeyCB.setItemText(2, _translate("MainWindow", "D"))
        self.sKeyCB.setItemText(3, _translate("MainWindow", "D#\\Eb"))
        self.sKeyCB.setItemText(4, _translate("MainWindow", "E"))
        self.sKeyCB.setItemText(5, _translate("MainWindow", "F"))
        self.sKeyCB.setItemText(6, _translate("MainWindow", "F#\\Gb"))
        self.sKeyCB.setItemText(7, _translate("MainWindow", "G"))
        self.sKeyCB.setItemText(8, _translate("MainWindow", "G#\\Ab"))
        self.sKeyCB.setItemText(9, _translate("MainWindow", "A"))
        self.sKeyCB.setItemText(10, _translate("MainWindow", "A#\\Bb"))
        self.sKeyCB.setItemText(11, _translate("MainWindow", "B\\Cb"))
        self.label_10.setText(_translate("MainWindow", "Scale"))
        self.sScaleCB.setItemText(0, _translate("MainWindow", "Major"))
        self.sScaleCB.setItemText(1, _translate("MainWindow", "Minor"))
        self.sScaleCB.setItemText(2, _translate("MainWindow", "Major Pent."))
        self.sScaleCB.setItemText(3, _translate("MainWindow", "Minor Pent."))
        self.sScaleCB.setItemText(4, _translate("MainWindow", "Blues"))
        self.sScaleCB.setItemText(5, _translate("MainWindow", "Dorian"))
        self.buildTabWidget.setTabText(self.buildTabWidget.indexOf(self.scaleTab), _translate("MainWindow", "Scale"))
        self.label_3.setText(_translate("MainWindow", "Key"))
        self.cKeyCB.setItemText(0, _translate("MainWindow", "C"))
        self.cKeyCB.setItemText(1, _translate("MainWindow", "C#\\Db"))
        self.cKeyCB.setItemText(2, _translate("MainWindow", "D"))
        self.cKeyCB.setItemText(3, _translate("MainWindow", "D#\\Eb"))
        self.cKeyCB.setItemText(4, _translate("MainWindow", "E"))
        self.cKeyCB.setItemText(5, _translate("MainWindow", "F"))
        self.cKeyCB.setItemText(6, _translate("MainWindow", "F#\\Gb"))
        self.cKeyCB.setItemText(7, _translate("MainWindow", "G"))
        self.cKeyCB.setItemText(8, _translate("MainWindow", "G#\\Ab"))
        self.cKeyCB.setItemText(9, _translate("MainWindow", "A"))
        self.cKeyCB.setItemText(10, _translate("MainWindow", "A#\\Bb"))
        self.cKeyCB.setItemText(11, _translate("MainWindow", "B\\Cb"))
        self.label_4.setText(_translate("MainWindow", "Chord"))
        self.cChordCB.setItemText(0, _translate("MainWindow", "Major"))
        self.cChordCB.setItemText(1, _translate("MainWindow", "Minor"))
        self.cChordCB.setItemText(2, _translate("MainWindow", "Augmented"))
        self.cChordCB.setItemText(3, _translate("MainWindow", "Diminished"))
        self.label_5.setText(_translate("MainWindow", "Add"))
        self.cAddCB.setItemText(0, _translate("MainWindow", "None"))
        self.cAddCB.setItemText(1, _translate("MainWindow", "6"))
        self.cAddCB.setItemText(2, _translate("MainWindow", "maj6"))
        self.cAddCB.setItemText(3, _translate("MainWindow", "7"))
        self.cAddCB.setItemText(4, _translate("MainWindow", "maj7"))
        self.buildTabWidget.setTabText(self.buildTabWidget.indexOf(self.chordTab), _translate("MainWindow", "Chord"))
        self.label_6.setText(_translate("MainWindow", "Key"))
        self.iKeyCB.setItemText(0, _translate("MainWindow", "C"))
        self.iKeyCB.setItemText(1, _translate("MainWindow", "C#\\Db"))
        self.iKeyCB.setItemText(2, _translate("MainWindow", "D"))
        self.iKeyCB.setItemText(3, _translate("MainWindow", "D#\\Eb"))
        self.iKeyCB.setItemText(4, _translate("MainWindow", "E"))
        self.iKeyCB.setItemText(5, _translate("MainWindow", "F"))
        self.iKeyCB.setItemText(6, _translate("MainWindow", "F#\\Gb"))
        self.iKeyCB.setItemText(7, _translate("MainWindow", "G"))
        self.iKeyCB.setItemText(8, _translate("MainWindow", "G#\\Ab"))
        self.iKeyCB.setItemText(9, _translate("MainWindow", "A"))
        self.iKeyCB.setItemText(10, _translate("MainWindow", "A#\\Bb"))
        self.iKeyCB.setItemText(11, _translate("MainWindow", "B\\Cb"))
        self.label_7.setText(_translate("MainWindow", "Interval"))
        self.iIntervalCB.setItemText(0, _translate("MainWindow", "Minor 2nd"))
        self.iIntervalCB.setItemText(1, _translate("MainWindow", "Major 2nd"))
        self.iIntervalCB.setItemText(2, _translate("MainWindow", "Minor 3rd"))
        self.iIntervalCB.setItemText(3, _translate("MainWindow", "Major 3rd"))
        self.iIntervalCB.setItemText(4, _translate("MainWindow", "4th"))
        self.iIntervalCB.setItemText(5, _translate("MainWindow", "Tritone"))
        self.iIntervalCB.setItemText(6, _translate("MainWindow", "5th"))
        self.iIntervalCB.setItemText(7, _translate("MainWindow", "Minor 6th"))
        self.iIntervalCB.setItemText(8, _translate("MainWindow", "Major 6th"))
        self.iIntervalCB.setItemText(9, _translate("MainWindow", "Minor 7th"))
        self.iIntervalCB.setItemText(10, _translate("MainWindow", "Major 7th"))
        self.iIntervalCB.setItemText(11, _translate("MainWindow", "Octave"))
        self.buildTabWidget.setTabText(self.buildTabWidget.indexOf(self.intervalTab), _translate("MainWindow", "Interval"))
        self.buildButton.setText(_translate("MainWindow", "Build"))
        self.listenButton.setText(_translate("MainWindow", "Listen"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Language"))
        self.sLanguageCB.setItemText(0, _translate("MainWindow", "English"))
        self.sLanguageCB.setItemText(1, _translate("MainWindow", "Русский"))
        self.label_2.setText(_translate("MainWindow", "Instrument"))
        self.sInstrumentCB.setItemText(0, _translate("MainWindow", "Piano"))
        self.sInstrumentCB.setItemText(1, _translate("MainWindow", "Guitar"))
        self.sLHint.setText(_translate("MainWindow", "Restart the app to apply language."))
        self.sResetButton.setText(_translate("MainWindow", "Reset"))
        self.sApplyButton.setText(_translate("MainWindow", "Apply"))
        self.eAvResult.setText(_translate("MainWindow", "Average result: 0"))
        self.eStartButton.setText(_translate("MainWindow", "Start"))
        self.eNListenButton.setText(_translate("MainWindow", "Listen"))
        self.eNSubmitButton.setText(_translate("MainWindow", "Submit"))
        self.eNNextButton.setText(_translate("MainWindow", "Next"))
        self.eNAnswer.setText(_translate("MainWindow", "Correct answer: "))
        self.eTabWidget.setTabText(self.eTabWidget.indexOf(self.tab), _translate("MainWindow", "Notes"))
        self.eIListenButton.setText(_translate("MainWindow", "Listen"))
        self.eISubmitButton.setText(_translate("MainWindow", "Submit"))
        self.eINextButton.setText(_translate("MainWindow", "Next"))
        self.eIAnswer.setText(_translate("MainWindow", "Correct answer: "))
        self.eTabWidget.setTabText(self.eTabWidget.indexOf(self.tab_2), _translate("MainWindow", "Intervals"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
